###Register User
POST  http://localhost:5000/user/register
Content-Type: application/json

{
    "name": "Mildred",
    "username": "Mildred",
    "email":"Mildred@gmail.com",
    "password":"123456789",
    "phone_number": "123456789"
}

###Login User
POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "email":"achieng@gmail.com",
    "password":"123456789"
}

###Update user
PUT  http://localhost:5000/user/update/5fbcef79-57dc-41b3-906a-317e5f004a15
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWlsZHJlZCIsInVzZXJuYW1lIjoiTWlsZHJlZCIsImVtYWlsIjoiTWlsZHJlZEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRCS1lGSTJiS3JWU3FWYml4dXNrZFF1SHdMcmZWblU5dUFFV2ZvRzlWbEd6aEIva3gyekVxSyIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjpudWxsLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJwcm9maWxlUGljIjpudWxsLCJpYXQiOjE2OTQ0MzQxMDIsImV4cCI6MTY5NDQ3MDEwMn0.va0XnKuBhTROPVm4-ubWLkKV_nX-QPDbTHCHyY2-ywo

{
    "name": "Achieng",
    "username": "achieng",
    "email":"achieng@gmail.com",
    "phone_number": "12345678"
}

###One User
POST  http://localhost:5000/user/oneUser/5fbcef79-57dc-41b3-906a-317e5f004a15


###Post
POST http://localhost:5000/posts/upload/5fbcef79-57dc-41b3-906a-317e5f004a15
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWNoaWVuZyIsInVzZXJuYW1lIjoiYWNoaWVuZyIsImVtYWlsIjoiYWNoaWVuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRCS1lGSTJiS3JWU3FWYml4dXNrZFF1SHdMcmZWblU5dUFFV2ZvRzlWbEd6aEIva3gyekVxSyIsInBob25lX251bWJlciI6MTIzNDU2NzgsInVwZGF0ZWRfYXQiOiIyMDIzLTA5LTExVDE1OjA5OjM0LjU0MFoiLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJwcm9maWxlUGljIjpudWxsLCJpYXQiOjE2OTQ0MzQzMDIsImV4cCI6MTY5NDQ3MDMwMn0.3M_cCpG86fYeHarNiBgmgGTLolk0Ygcxhqh3cwf-OOU

{
    "postName": "It is presentation time at 1510hrs"
}

###All Posts
GET http://localhost:5000/posts/allPosts



###Get one Post
GET http://localhost:5000/posts/onepost/f153fa47-4c7a-4403-8e54-a7bd4d31d995
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWNoaWVuZyIsInVzZXJuYW1lIjoiYWNoaWVuZyIsImVtYWlsIjoiYWNoaWVuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRCS1lGSTJiS3JWU3FWYml4dXNrZFF1SHdMcmZWblU5dUFFV2ZvRzlWbEd6aEIva3gyekVxSyIsInBob25lX251bWJlciI6MTIzNDU2NzgsInVwZGF0ZWRfYXQiOiIyMDIzLTA5LTExVDE1OjA5OjM0LjU0MFoiLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJwcm9maWxlUGljIjpudWxsLCJpYXQiOjE2OTQ0MzQzMDIsImV4cCI6MTY5NDQ3MDMwMn0.3M_cCpG86fYeHarNiBgmgGTLolk0Ygcxhqh3cwf-OOU


###Get posts by userId
GET http://localhost:5000/posts/yourposts/107a504d-cfad-43bc-afa1-e0b34eb0e307
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE


###Delete post
DELETE http://localhost:5000/posts/deletepost/107a504d-cfad-43bc-afa1-e0b34eb0e307/f153fa47-4c7a-4403-8e54-a7bd4d31d995
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE


###Comment
POST  http://localhost:5000/comments/comment/107a504d-cfad-43bc-afa1-e0b34eb0e307/a955f8f4-9972-43d7-a3db-1818e9f28729
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE

{
    "commentText": "Yes the presentation is on going"
}

###get comments by of a post
GET http://localhost:5000/comments/postscomments/a955f8f4-9972-43d7-a3db-1818e9f28729


###get your comments 
GET http://localhost:5000/comments/yourcomments/107a504d-cfad-43bc-afa1-e0b34eb0e307
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Delete Comment
DELETE http://localhost:5000/comments/deletecomment/107a504d-cfad-43bc-afa1-e0b34eb0e307/ecc0b450-e937-4dbd-bca4-b738a2dfddeb
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Follow a person
POST http://localhost:5000/follow/follow/107a504d-cfad-43bc-afa1-e0b34eb0e307/5fbcef79-57dc-41b3-906a-317e5f004a15
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Unfollow a person
DELETE http://localhost:5000/follow/unfollow/107a504d-cfad-43bc-afa1-e0b34eb0e307/44d3d762-e991-4f4b-ba60-af0dedef3def
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE




###Get Persons to Follow
GET http://localhost:5000/follow/personstofollow/107a504d-cfad-43bc-afa1-e0b34eb0e307
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Persons you are following
GET http://localhost:5000/follow/personsyouarefollowing/107a504d-cfad-43bc-afa1-e0b34eb0e307
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Your Followers
GET http://localhost:5000/follow/yourfollowers/107a504d-cfad-43bc-afa1-e0b34eb0e307
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE




### reset password
POST  http://localhost:5000/reset/resetPassword
Content-Type: application/json

{
    "email": "ngatiamwai25@gmail.com"   
}

### setting new password
POST  http://localhost:5000/reset/updatePassword
Content-Type: application/json

{
    "resetToken": "53d18742-3609-4f7a-880f-ece98a6f4eec",
    "newPassword": "1234567890"
    
}


###Like Post
GET http://localhost:5000/like/likepost/107a504d-cfad-43bc-afa1-e0b34eb0e307/4f305c38-a99a-46f6-8485-f746c2d385a5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE



###Unlike Post
DELETE  http://localhost:5000/like/unlikepost/107a504d-cfad-43bc-afa1-e0b34eb0e307/4f305c38-a99a-46f6-8485-f746c2d385a5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzQ0MzksImV4cCI6MTY5NDQ3MDQzOX0.NDtgreA38UTyJU24MaFnW8Gpf56ephl-qHyuMxJsXyE


###Subcomment
POST http://localhost:5000/comments/subcomment/107a504d-cfad-43bc-afa1-e0b34eb0e307/9faa8556-be3f-4ed6-bff6-d15193f7d6c8
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdhaSIsInVzZXJuYW1lIjoibXdhaSIsImVtYWlsIjoibXdhaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSR4WHgzUXpuZktMZDA0SHVFcVB0b21lZE9ZbFFTQ3hPeHZxaW1vbmhtRmVxQUlVZ3JMWWFWNiIsInBob25lX251bWJlciI6MTIzNDU2Nzg5LCJ1cGRhdGVkX2F0IjoiMjAyMy0wOS0wNlQxOTowMjoxMS45MjBaIiwicmVzZXRUb2tlbiI6Ijk0YzI1MmZiLTM2NDAtNDhiOS1hZGQwLTc3NGNhM2JkZDA0NCIsInJlc2V0VG9rZW5FeHBpcnkiOiIyMDIzLTA5LTA4VDE0OjAwOjQwLjg1M1oiLCJwcm9maWxlUGljIjoiaHR0cDovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kaGdzOHRoengvaW1hZ2UvdXBsb2FkL3YxNjk0MDE2MTM0L2pkaThqMnBhaGpxcGdmbnB4b2t3LndlYnAiLCJpYXQiOjE2OTQ0MzE0NTMsImV4cCI6MTY5NDQ2NzQ1M30.9Rdx8Fqvxj3OctxgItmETNNe_FvmSXAhGbPJ_CRgdmE


{
    "subCommentText" : "How are you?"
}